// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bloaty.proto

#include "bloaty.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_bloaty_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_bloaty_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Regex;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_bloaty_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_CustomDataSource;
}  // namespace protobuf_bloaty_2eproto
namespace bloaty {
class OptionsDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Options>
      _instance;
} _Options_default_instance_;
class CustomDataSourceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CustomDataSource>
      _instance;
} _CustomDataSource_default_instance_;
class RegexDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Regex>
      _instance;
} _Regex_default_instance_;
}  // namespace bloaty
namespace protobuf_bloaty_2eproto {
static void InitDefaultsOptions() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bloaty::_Options_default_instance_;
    new (ptr) ::bloaty::Options();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bloaty::Options::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Options =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsOptions}, {
      &protobuf_bloaty_2eproto::scc_info_CustomDataSource.base,}};

static void InitDefaultsCustomDataSource() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bloaty::_CustomDataSource_default_instance_;
    new (ptr) ::bloaty::CustomDataSource();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bloaty::CustomDataSource::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CustomDataSource =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCustomDataSource}, {
      &protobuf_bloaty_2eproto::scc_info_Regex.base,}};

static void InitDefaultsRegex() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::bloaty::_Regex_default_instance_;
    new (ptr) ::bloaty::Regex();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::bloaty::Regex::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Regex =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRegex}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Options.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CustomDataSource.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Regex.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, filename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, base_filename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, debug_filename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, data_source_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, max_rows_per_level_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, demangle_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, sort_by_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, verbose_level_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, debug_vmaddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, debug_fileoff_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, custom_data_source_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Options, disassemble_function_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  6,
  1,
  2,
  5,
  3,
  4,
  ~0u,
  0,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::CustomDataSource, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::CustomDataSource, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::CustomDataSource, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::CustomDataSource, base_data_source_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::CustomDataSource, rewrite_),
  0,
  1,
  ~0u,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Regex, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Regex, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Regex, pattern_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::bloaty::Regex, replacement_),
  0,
  1,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 17, sizeof(::bloaty::Options)},
  { 29, 37, sizeof(::bloaty::CustomDataSource)},
  { 40, 47, sizeof(::bloaty::Regex)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::bloaty::_Options_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bloaty::_CustomDataSource_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::bloaty::_Regex_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "bloaty.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014bloaty.proto\022\006bloaty\"\222\004\n\007Options\022\020\n\010fi"
      "lename\030\001 \003(\t\022\025\n\rbase_filename\030\002 \003(\t\022\026\n\016d"
      "ebug_filename\030\n \003(\t\022\023\n\013data_source\030\003 \003(\t"
      "\022\036\n\022max_rows_per_level\030\004 \001(\003:\00220\022:\n\010dema"
      "ngle\030\005 \001(\0162\030.bloaty.Options.Demangle:\016DE"
      "MANGLE_SHORT\0224\n\007sort_by\030\006 \001(\0162\026.bloaty.O"
      "ptions.SortBy:\013SORTBY_BOTH\022\025\n\rverbose_le"
      "vel\030\007 \001(\005\022\024\n\014debug_vmaddr\030\013 \001(\004\022\025\n\rdebug"
      "_fileoff\030\014 \001(\004\0224\n\022custom_data_source\030\010 \003"
      "(\0132\030.bloaty.CustomDataSource\022\034\n\024disassem"
      "ble_function\030\t \001(\t\"D\n\010Demangle\022\022\n\016DEMANG"
      "LE_SHORT\020\000\022\021\n\rDEMANGLE_FULL\020\001\022\021\n\rDEMANGL"
      "E_NONE\020\002\"A\n\006SortBy\022\017\n\013SORTBY_BOTH\020\000\022\021\n\rS"
      "ORTBY_VMSIZE\020\001\022\023\n\017SORTBY_FILESIZE\020\002\"Z\n\020C"
      "ustomDataSource\022\014\n\004name\030\001 \001(\t\022\030\n\020base_da"
      "ta_source\030\002 \001(\t\022\036\n\007rewrite\030\003 \003(\0132\r.bloat"
      "y.Regex\"-\n\005Regex\022\017\n\007pattern\030\001 \001(\t\022\023\n\013rep"
      "lacement\030\002 \001(\t"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 694);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "bloaty.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_bloaty_2eproto
namespace bloaty {
const ::google::protobuf::EnumDescriptor* Options_Demangle_descriptor() {
  protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_bloaty_2eproto::file_level_enum_descriptors[0];
}
bool Options_Demangle_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Options_Demangle Options::DEMANGLE_SHORT;
const Options_Demangle Options::DEMANGLE_FULL;
const Options_Demangle Options::DEMANGLE_NONE;
const Options_Demangle Options::Demangle_MIN;
const Options_Demangle Options::Demangle_MAX;
const int Options::Demangle_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* Options_SortBy_descriptor() {
  protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_bloaty_2eproto::file_level_enum_descriptors[1];
}
bool Options_SortBy_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Options_SortBy Options::SORTBY_BOTH;
const Options_SortBy Options::SORTBY_VMSIZE;
const Options_SortBy Options::SORTBY_FILESIZE;
const Options_SortBy Options::SortBy_MIN;
const Options_SortBy Options::SortBy_MAX;
const int Options::SortBy_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void Options::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Options::kFilenameFieldNumber;
const int Options::kBaseFilenameFieldNumber;
const int Options::kDebugFilenameFieldNumber;
const int Options::kDataSourceFieldNumber;
const int Options::kMaxRowsPerLevelFieldNumber;
const int Options::kDemangleFieldNumber;
const int Options::kSortByFieldNumber;
const int Options::kVerboseLevelFieldNumber;
const int Options::kDebugVmaddrFieldNumber;
const int Options::kDebugFileoffFieldNumber;
const int Options::kCustomDataSourceFieldNumber;
const int Options::kDisassembleFunctionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Options::Options()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bloaty_2eproto::scc_info_Options.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bloaty.Options)
}
Options::Options(const Options& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      filename_(from.filename_),
      base_filename_(from.base_filename_),
      data_source_(from.data_source_),
      custom_data_source_(from.custom_data_source_),
      debug_filename_(from.debug_filename_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  disassemble_function_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_disassemble_function()) {
    disassemble_function_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.disassemble_function_);
  }
  ::memcpy(&demangle_, &from.demangle_,
    static_cast<size_t>(reinterpret_cast<char*>(&max_rows_per_level_) -
    reinterpret_cast<char*>(&demangle_)) + sizeof(max_rows_per_level_));
  // @@protoc_insertion_point(copy_constructor:bloaty.Options)
}

void Options::SharedCtor() {
  disassemble_function_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&demangle_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&verbose_level_) -
      reinterpret_cast<char*>(&demangle_)) + sizeof(verbose_level_));
  max_rows_per_level_ = GOOGLE_LONGLONG(20);
}

Options::~Options() {
  // @@protoc_insertion_point(destructor:bloaty.Options)
  SharedDtor();
}

void Options::SharedDtor() {
  disassemble_function_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Options::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Options::descriptor() {
  ::protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bloaty_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Options& Options::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bloaty_2eproto::scc_info_Options.base);
  return *internal_default_instance();
}


void Options::Clear() {
// @@protoc_insertion_point(message_clear_start:bloaty.Options)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filename_.Clear();
  base_filename_.Clear();
  data_source_.Clear();
  custom_data_source_.Clear();
  debug_filename_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    disassemble_function_.ClearNonDefaultToEmptyNoArena();
  }
  if (cached_has_bits & 126u) {
    ::memset(&demangle_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&verbose_level_) -
        reinterpret_cast<char*>(&demangle_)) + sizeof(verbose_level_));
    max_rows_per_level_ = GOOGLE_LONGLONG(20);
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Options::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bloaty.Options)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string filename = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_filename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->filename(this->filename_size() - 1).data(),
            static_cast<int>(this->filename(this->filename_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.Options.filename");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string base_filename = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_base_filename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->base_filename(this->base_filename_size() - 1).data(),
            static_cast<int>(this->base_filename(this->base_filename_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.Options.base_filename");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string data_source = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_data_source()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->data_source(this->data_source_size() - 1).data(),
            static_cast<int>(this->data_source(this->data_source_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.Options.data_source");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int64 max_rows_per_level = 4 [default = 20];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          set_has_max_rows_per_level();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &max_rows_per_level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .bloaty.Options.Demangle demangle = 5 [default = DEMANGLE_SHORT];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::bloaty::Options_Demangle_IsValid(value)) {
            set_demangle(static_cast< ::bloaty::Options_Demangle >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                5, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional .bloaty.Options.SortBy sort_by = 6 [default = SORTBY_BOTH];
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::bloaty::Options_SortBy_IsValid(value)) {
            set_sort_by(static_cast< ::bloaty::Options_SortBy >(value));
          } else {
            mutable_unknown_fields()->AddVarint(
                6, static_cast< ::google::protobuf::uint64>(value));
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 verbose_level = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {
          set_has_verbose_level();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &verbose_level_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .bloaty.CustomDataSource custom_data_source = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_custom_data_source()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string disassemble_function = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_disassemble_function()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->disassemble_function().data(), static_cast<int>(this->disassemble_function().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.Options.disassemble_function");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string debug_filename = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_debug_filename()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->debug_filename(this->debug_filename_size() - 1).data(),
            static_cast<int>(this->debug_filename(this->debug_filename_size() - 1).length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.Options.debug_filename");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint64 debug_vmaddr = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {
          set_has_debug_vmaddr();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &debug_vmaddr_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint64 debug_fileoff = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {
          set_has_debug_fileoff();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &debug_fileoff_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bloaty.Options)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bloaty.Options)
  return false;
#undef DO_
}

void Options::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bloaty.Options)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string filename = 1;
  for (int i = 0, n = this->filename_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename(i).data(), static_cast<int>(this->filename(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.filename");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->filename(i), output);
  }

  // repeated string base_filename = 2;
  for (int i = 0, n = this->base_filename_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->base_filename(i).data(), static_cast<int>(this->base_filename(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.base_filename");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->base_filename(i), output);
  }

  // repeated string data_source = 3;
  for (int i = 0, n = this->data_source_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data_source(i).data(), static_cast<int>(this->data_source(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.data_source");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->data_source(i), output);
  }

  cached_has_bits = _has_bits_[0];
  // optional int64 max_rows_per_level = 4 [default = 20];
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->max_rows_per_level(), output);
  }

  // optional .bloaty.Options.Demangle demangle = 5 [default = DEMANGLE_SHORT];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->demangle(), output);
  }

  // optional .bloaty.Options.SortBy sort_by = 6 [default = SORTBY_BOTH];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      6, this->sort_by(), output);
  }

  // optional int32 verbose_level = 7;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->verbose_level(), output);
  }

  // repeated .bloaty.CustomDataSource custom_data_source = 8;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->custom_data_source_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8,
      this->custom_data_source(static_cast<int>(i)),
      output);
  }

  // optional string disassemble_function = 9;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->disassemble_function().data(), static_cast<int>(this->disassemble_function().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.disassemble_function");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->disassemble_function(), output);
  }

  // repeated string debug_filename = 10;
  for (int i = 0, n = this->debug_filename_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->debug_filename(i).data(), static_cast<int>(this->debug_filename(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.debug_filename");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      10, this->debug_filename(i), output);
  }

  // optional uint64 debug_vmaddr = 11;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(11, this->debug_vmaddr(), output);
  }

  // optional uint64 debug_fileoff = 12;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(12, this->debug_fileoff(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:bloaty.Options)
}

::google::protobuf::uint8* Options::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bloaty.Options)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string filename = 1;
  for (int i = 0, n = this->filename_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->filename(i).data(), static_cast<int>(this->filename(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.filename");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->filename(i), target);
  }

  // repeated string base_filename = 2;
  for (int i = 0, n = this->base_filename_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->base_filename(i).data(), static_cast<int>(this->base_filename(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.base_filename");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->base_filename(i), target);
  }

  // repeated string data_source = 3;
  for (int i = 0, n = this->data_source_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data_source(i).data(), static_cast<int>(this->data_source(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.data_source");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->data_source(i), target);
  }

  cached_has_bits = _has_bits_[0];
  // optional int64 max_rows_per_level = 4 [default = 20];
  if (cached_has_bits & 0x00000040u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->max_rows_per_level(), target);
  }

  // optional .bloaty.Options.Demangle demangle = 5 [default = DEMANGLE_SHORT];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->demangle(), target);
  }

  // optional .bloaty.Options.SortBy sort_by = 6 [default = SORTBY_BOTH];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      6, this->sort_by(), target);
  }

  // optional int32 verbose_level = 7;
  if (cached_has_bits & 0x00000020u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->verbose_level(), target);
  }

  // repeated .bloaty.CustomDataSource custom_data_source = 8;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->custom_data_source_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        8, this->custom_data_source(static_cast<int>(i)), deterministic, target);
  }

  // optional string disassemble_function = 9;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->disassemble_function().data(), static_cast<int>(this->disassemble_function().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.disassemble_function");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->disassemble_function(), target);
  }

  // repeated string debug_filename = 10;
  for (int i = 0, n = this->debug_filename_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->debug_filename(i).data(), static_cast<int>(this->debug_filename(i).length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Options.debug_filename");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(10, this->debug_filename(i), target);
  }

  // optional uint64 debug_vmaddr = 11;
  if (cached_has_bits & 0x00000008u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(11, this->debug_vmaddr(), target);
  }

  // optional uint64 debug_fileoff = 12;
  if (cached_has_bits & 0x00000010u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(12, this->debug_fileoff(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bloaty.Options)
  return target;
}

size_t Options::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bloaty.Options)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated string filename = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->filename_size());
  for (int i = 0, n = this->filename_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->filename(i));
  }

  // repeated string base_filename = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->base_filename_size());
  for (int i = 0, n = this->base_filename_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->base_filename(i));
  }

  // repeated string data_source = 3;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->data_source_size());
  for (int i = 0, n = this->data_source_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->data_source(i));
  }

  // repeated .bloaty.CustomDataSource custom_data_source = 8;
  {
    unsigned int count = static_cast<unsigned int>(this->custom_data_source_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->custom_data_source(static_cast<int>(i)));
    }
  }

  // repeated string debug_filename = 10;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->debug_filename_size());
  for (int i = 0, n = this->debug_filename_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->debug_filename(i));
  }

  if (_has_bits_[0 / 32] & 127u) {
    // optional string disassemble_function = 9;
    if (has_disassemble_function()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->disassemble_function());
    }

    // optional .bloaty.Options.Demangle demangle = 5 [default = DEMANGLE_SHORT];
    if (has_demangle()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->demangle());
    }

    // optional .bloaty.Options.SortBy sort_by = 6 [default = SORTBY_BOTH];
    if (has_sort_by()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->sort_by());
    }

    // optional uint64 debug_vmaddr = 11;
    if (has_debug_vmaddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->debug_vmaddr());
    }

    // optional uint64 debug_fileoff = 12;
    if (has_debug_fileoff()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->debug_fileoff());
    }

    // optional int32 verbose_level = 7;
    if (has_verbose_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->verbose_level());
    }

    // optional int64 max_rows_per_level = 4 [default = 20];
    if (has_max_rows_per_level()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->max_rows_per_level());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Options::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bloaty.Options)
  GOOGLE_DCHECK_NE(&from, this);
  const Options* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Options>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bloaty.Options)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bloaty.Options)
    MergeFrom(*source);
  }
}

void Options::MergeFrom(const Options& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bloaty.Options)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  filename_.MergeFrom(from.filename_);
  base_filename_.MergeFrom(from.base_filename_);
  data_source_.MergeFrom(from.data_source_);
  custom_data_source_.MergeFrom(from.custom_data_source_);
  debug_filename_.MergeFrom(from.debug_filename_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 127u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_disassemble_function();
      disassemble_function_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.disassemble_function_);
    }
    if (cached_has_bits & 0x00000002u) {
      demangle_ = from.demangle_;
    }
    if (cached_has_bits & 0x00000004u) {
      sort_by_ = from.sort_by_;
    }
    if (cached_has_bits & 0x00000008u) {
      debug_vmaddr_ = from.debug_vmaddr_;
    }
    if (cached_has_bits & 0x00000010u) {
      debug_fileoff_ = from.debug_fileoff_;
    }
    if (cached_has_bits & 0x00000020u) {
      verbose_level_ = from.verbose_level_;
    }
    if (cached_has_bits & 0x00000040u) {
      max_rows_per_level_ = from.max_rows_per_level_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void Options::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bloaty.Options)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Options::CopyFrom(const Options& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bloaty.Options)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Options::IsInitialized() const {
  return true;
}

void Options::Swap(Options* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Options::InternalSwap(Options* other) {
  using std::swap;
  filename_.InternalSwap(CastToBase(&other->filename_));
  base_filename_.InternalSwap(CastToBase(&other->base_filename_));
  data_source_.InternalSwap(CastToBase(&other->data_source_));
  CastToBase(&custom_data_source_)->InternalSwap(CastToBase(&other->custom_data_source_));
  debug_filename_.InternalSwap(CastToBase(&other->debug_filename_));
  disassemble_function_.Swap(&other->disassemble_function_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(demangle_, other->demangle_);
  swap(sort_by_, other->sort_by_);
  swap(debug_vmaddr_, other->debug_vmaddr_);
  swap(debug_fileoff_, other->debug_fileoff_);
  swap(verbose_level_, other->verbose_level_);
  swap(max_rows_per_level_, other->max_rows_per_level_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Options::GetMetadata() const {
  protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bloaty_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CustomDataSource::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CustomDataSource::kNameFieldNumber;
const int CustomDataSource::kBaseDataSourceFieldNumber;
const int CustomDataSource::kRewriteFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CustomDataSource::CustomDataSource()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bloaty_2eproto::scc_info_CustomDataSource.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bloaty.CustomDataSource)
}
CustomDataSource::CustomDataSource(const CustomDataSource& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      rewrite_(from.rewrite_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_name()) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  base_data_source_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_base_data_source()) {
    base_data_source_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.base_data_source_);
  }
  // @@protoc_insertion_point(copy_constructor:bloaty.CustomDataSource)
}

void CustomDataSource::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  base_data_source_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CustomDataSource::~CustomDataSource() {
  // @@protoc_insertion_point(destructor:bloaty.CustomDataSource)
  SharedDtor();
}

void CustomDataSource::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  base_data_source_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CustomDataSource::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CustomDataSource::descriptor() {
  ::protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bloaty_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CustomDataSource& CustomDataSource::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bloaty_2eproto::scc_info_CustomDataSource.base);
  return *internal_default_instance();
}


void CustomDataSource::Clear() {
// @@protoc_insertion_point(message_clear_start:bloaty.CustomDataSource)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rewrite_.Clear();
  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      name_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      base_data_source_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool CustomDataSource::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bloaty.CustomDataSource)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.CustomDataSource.name");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string base_data_source = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_base_data_source()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->base_data_source().data(), static_cast<int>(this->base_data_source().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.CustomDataSource.base_data_source");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .bloaty.Regex rewrite = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_rewrite()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bloaty.CustomDataSource)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bloaty.CustomDataSource)
  return false;
#undef DO_
}

void CustomDataSource::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bloaty.CustomDataSource)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.CustomDataSource.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // optional string base_data_source = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->base_data_source().data(), static_cast<int>(this->base_data_source().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.CustomDataSource.base_data_source");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->base_data_source(), output);
  }

  // repeated .bloaty.Regex rewrite = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->rewrite_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->rewrite(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:bloaty.CustomDataSource)
}

::google::protobuf::uint8* CustomDataSource::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bloaty.CustomDataSource)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string name = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.CustomDataSource.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // optional string base_data_source = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->base_data_source().data(), static_cast<int>(this->base_data_source().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.CustomDataSource.base_data_source");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->base_data_source(), target);
  }

  // repeated .bloaty.Regex rewrite = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->rewrite_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->rewrite(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bloaty.CustomDataSource)
  return target;
}

size_t CustomDataSource::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bloaty.CustomDataSource)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .bloaty.Regex rewrite = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->rewrite_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->rewrite(static_cast<int>(i)));
    }
  }

  if (_has_bits_[0 / 32] & 3u) {
    // optional string name = 1;
    if (has_name()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->name());
    }

    // optional string base_data_source = 2;
    if (has_base_data_source()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->base_data_source());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CustomDataSource::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bloaty.CustomDataSource)
  GOOGLE_DCHECK_NE(&from, this);
  const CustomDataSource* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CustomDataSource>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bloaty.CustomDataSource)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bloaty.CustomDataSource)
    MergeFrom(*source);
  }
}

void CustomDataSource::MergeFrom(const CustomDataSource& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bloaty.CustomDataSource)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  rewrite_.MergeFrom(from.rewrite_);
  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_name();
      name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_base_data_source();
      base_data_source_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.base_data_source_);
    }
  }
}

void CustomDataSource::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bloaty.CustomDataSource)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CustomDataSource::CopyFrom(const CustomDataSource& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bloaty.CustomDataSource)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CustomDataSource::IsInitialized() const {
  return true;
}

void CustomDataSource::Swap(CustomDataSource* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CustomDataSource::InternalSwap(CustomDataSource* other) {
  using std::swap;
  CastToBase(&rewrite_)->InternalSwap(CastToBase(&other->rewrite_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  base_data_source_.Swap(&other->base_data_source_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CustomDataSource::GetMetadata() const {
  protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bloaty_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Regex::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Regex::kPatternFieldNumber;
const int Regex::kReplacementFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Regex::Regex()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_bloaty_2eproto::scc_info_Regex.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:bloaty.Regex)
}
Regex::Regex(const Regex& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  pattern_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_pattern()) {
    pattern_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pattern_);
  }
  replacement_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_replacement()) {
    replacement_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.replacement_);
  }
  // @@protoc_insertion_point(copy_constructor:bloaty.Regex)
}

void Regex::SharedCtor() {
  pattern_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replacement_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Regex::~Regex() {
  // @@protoc_insertion_point(destructor:bloaty.Regex)
  SharedDtor();
}

void Regex::SharedDtor() {
  pattern_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  replacement_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Regex::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Regex::descriptor() {
  ::protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bloaty_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Regex& Regex::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_bloaty_2eproto::scc_info_Regex.base);
  return *internal_default_instance();
}


void Regex::Clear() {
// @@protoc_insertion_point(message_clear_start:bloaty.Regex)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      pattern_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      replacement_.ClearNonDefaultToEmptyNoArena();
    }
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool Regex::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:bloaty.Regex)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string pattern = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pattern()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->pattern().data(), static_cast<int>(this->pattern().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.Regex.pattern");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string replacement = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_replacement()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->replacement().data(), static_cast<int>(this->replacement().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "bloaty.Regex.replacement");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:bloaty.Regex)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:bloaty.Regex)
  return false;
#undef DO_
}

void Regex::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:bloaty.Regex)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string pattern = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pattern().data(), static_cast<int>(this->pattern().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Regex.pattern");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->pattern(), output);
  }

  // optional string replacement = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->replacement().data(), static_cast<int>(this->replacement().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Regex.replacement");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->replacement(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:bloaty.Regex)
}

::google::protobuf::uint8* Regex::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:bloaty.Regex)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string pattern = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pattern().data(), static_cast<int>(this->pattern().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Regex.pattern");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->pattern(), target);
  }

  // optional string replacement = 2;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->replacement().data(), static_cast<int>(this->replacement().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "bloaty.Regex.replacement");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->replacement(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:bloaty.Regex)
  return target;
}

size_t Regex::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:bloaty.Regex)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 3u) {
    // optional string pattern = 1;
    if (has_pattern()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->pattern());
    }

    // optional string replacement = 2;
    if (has_replacement()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->replacement());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Regex::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:bloaty.Regex)
  GOOGLE_DCHECK_NE(&from, this);
  const Regex* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Regex>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:bloaty.Regex)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:bloaty.Regex)
    MergeFrom(*source);
  }
}

void Regex::MergeFrom(const Regex& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:bloaty.Regex)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 3u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_pattern();
      pattern_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pattern_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_replacement();
      replacement_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.replacement_);
    }
  }
}

void Regex::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:bloaty.Regex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Regex::CopyFrom(const Regex& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bloaty.Regex)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Regex::IsInitialized() const {
  return true;
}

void Regex::Swap(Regex* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Regex::InternalSwap(Regex* other) {
  using std::swap;
  pattern_.Swap(&other->pattern_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  replacement_.Swap(&other->replacement_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Regex::GetMetadata() const {
  protobuf_bloaty_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_bloaty_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace bloaty
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bloaty::Options* Arena::CreateMaybeMessage< ::bloaty::Options >(Arena* arena) {
  return Arena::CreateInternal< ::bloaty::Options >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bloaty::CustomDataSource* Arena::CreateMaybeMessage< ::bloaty::CustomDataSource >(Arena* arena) {
  return Arena::CreateInternal< ::bloaty::CustomDataSource >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::bloaty::Regex* Arena::CreateMaybeMessage< ::bloaty::Regex >(Arena* arena) {
  return Arena::CreateInternal< ::bloaty::Regex >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
